# Generated by Django 4.1.7 on 2024-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='foto_final',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='foto_inicial',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
