# Generated by Django 3.2 on 2024-04-09 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_evento_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_resolucion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
