# Generated by Django 3.2 on 2024-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_fecha_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_resolucion',
            field=models.DateTimeField(default=None),
        ),
    ]
