# Generated by Django 5.0.1 on 2024-04-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_fecha_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nombre_empleado',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
